# Generated by Django 3.2.8 on 2021-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='books/pdf')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/cover')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
